dist: trusty
language: go
sudo: required
go:
 - 1.8
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y gdal-bin libgdal-dev
 - go get github.com/mattn/goveralls
script:
 - $HOME/gopath/bin/goveralls -service=travis-ci
